### ISSUE TITLE
Date display frontend

### ISSUE THREAD

**Issue by StevePuts** [WOIDMO/WoMo-FrontEnd-V1#4]
Dates are no longer readable on the Dash slider. If someone smarter than me knows how to rotate the labels, that'd be great.

https://www.woidmo.org/home/womo/womo-united-states/

**Comment by sweta1486** [comment]
Fix is under date_display_fix branch. Please check.

**Comment by StevePuts** [comment]
That looks a whole lot better. Could you please do SouthAm and US as well?

**Comment by sweta1486** [comment]
Fixed SouthAm and US date slider display under date_display_fix branch. Please check.

**Comment by StevePuts** [comment]
Works perfectly, Thank you!
